### ISSUE TITLE
Translated version is chosen over native version

### ISSUE THREAD

**Issue by lordi** [cccc/plugin.video.media-ccc-de#3]
When I select a video from 32c3 conference, the translated version is chosen over the native version.

I dug around the source a bit and found out that the key ``translated`` is used, which is not part of the JSON api (anymore?). Rather, the key ``language`` exists, with the values ``en``, ``de``, ``en-de``. For instance, see https://api.media.ccc.de/public/events/2862

It could be a problem because there is no way to distinguish native from translated, do you have any idea? In any case, it would be helpful if the version with the largest number of audio streams is chosen so that one can select the audio stream within the Kodi player.

**Comment by manno** [comment]
The streaming API provides information on translations. However the media.ccc.de API for recordings did not.

I'm deploying a change which will add 'original_language' to the 'event' JSON.

**Comment by TobiX** [comment]
This should select the correct videos again. Please try the current development version: http://is.gd/ccckodi

**Comment by lordi** [comment]
Thanks for looking into it, the dev version works correctly!

**Comment by lordi** [comment]
Sorry for waking the dead, but in some cases it still does choose the translated version (single audio stream). For example with https://api.media.ccc.de/public/events/2939

**Comment by TobiX** [comment]
That is a very unfortunate situation, which will fix itself over time... There are currently only 3 recordings connected with this event: The HD version with 2 audio tracks and 2 "web" HD versions with each one audio track. The selection process gets a bit hairy in this case, since your client prefers SD versions, but there is no SD version yet. This probably needs to be fixed in the API...

**Comment by eNBeWe** [comment]
I would like to have this behavior adjustable. Personally I would rate the languages as "bilingual first, native second, translated last" but other users would probably prefer a single language only. Could you maybe implement a way to modify the selection of the corresponding video?

**Comment by TobiX** [comment]
@eNBeWe Currently not. Please open a new ticket for this, if you really consider this useful.

I will select the "best" (multi-audio) file for now and don't plan to expose any settings to change this. There are multiple reasons for this:

First, the single-audio-files might be removed in the future (they only exist for the web player, since browsers lack the ability to switch audio tracks at the moment) and then such a feature is useless.

Second, it doesn't save any significant amount of bandwidth, which might be a reason why somebody wants to select a file with fewer tracks. As an example, taking the talk from above (https://api.media.ccc.de/public/events/2939), here are all the HD files:
- en-de: 526 MiB, 1355 Kbps
- de-web: 492 MiB, 1269 Kbps
- en-web: 493 MiB, 1270 Kbps

Since those only differ in the audio tracks, when your are using the combined file, you only download 32.3 MiB (6%) or 32.1 MiB (6%) extra...
